matrix:
  include:
    - os: linux
      dist: xenial
      language: python
      python: '2.7'

    - os: linux
      dist: xenial
      language: python
      python: '3.6'

    - os: windows
      language: shell

    - os: osx
      language: shell

addons:
  apt:
    packages:
    - ffmpeg
    - sox
  homebrew:
    packages:
    - python
    - ffmpeg
    - sox

before_install: |
  if [ $TRAVIS_OS_NAME == 'windows' ]
  then
    set -e

    export PATH=$PATH:$TRAVIS_BUILD_DIR
    echo $PATH

    wget https://downloads.sourceforge.net/project/sox/sox/14.4.2/sox-14.4.2-win32.exe
    sox --version

    wget https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-4.1-win64-static.zip
    unzip -j ffmpeg-4.1-win64-static.zip
    ffmpeg -version

    choco install miniconda3 --params="'/AddToPath:1'"
    export PATH="/c/tools/miniconda3/scripts:/c/tools/miniconda3/:$PATH"
  fi

install:
- pip install .[test]

before_script: |
  pip install pytest coverage flake8 flake8-isort
  pip install flake8-bugbear || true

script:
# TODO - flake8 --disable-noqa
- coverage run -m pytest
- coverage report

deploy:
  provider: pypi
  user: carlthome
  skip_cleanup: true
  distributions: 'sdist bdist_wheel'
  skip_existing: true
  on:
    tags: true
    branch: master
  password:
    secure: EIVQp6DdA6CzKyIuFwzBekGmab/XUUs/9uFK6N1ejQA2219b3NNmogbkvFX1ZWE1sRmhA5PXV5vdToljAXfvL76AyVW01MNT5i6HLb1S4XzwuJYVdGBSFTQYcvgOLBz6yrkAwyuDZ6E9FLGQYEq51+SmD1yA531u8HA24l/RLozLY4cpnNIDoLsKtb9pj20LlwcprmTYFZBIL153z2oap975Vb09QV2qqJ0cL5irjGCUqI4spkzVY2QjA6TnfN0xwLw5XoESJoTY3R8L3cJ8B4JhvUwNsxNZxLY8ik22iRYQ+vUxGbpzYSDZ9WJsPzEqzRf6JHMnydF4qVH9kbXkBPNCUVh/AkBrXbE8YvbyO9P4mwoc55y7Ikpyk4Z5NuJQDVnGvcnySIvnhmNLQk6g1fpKZpydivWN+ZQEyVkCETApNOzMqzOqZaj+Z2my87Kn5rlwhELSNQGygudxtqaBh7EmDmUBYXBMaRIWsu6nquODlwLqImJkHaLH7rAmHQphIppO/QmCqVunFA+UPj+ZMUa7unqnTXuiMefCruTaVH0BAcrrNG8vx49O6rrhg3cW1dPkNb3oGOXuynwN+wXF2lBnfIqTube02hO5YcfyDQW7O9Hru/lBA1j2/n3PMn6TVoRTVqV/+SzU28XeoDOcbqhOMoeWFRrq90Fe9mLpP78=
