os:
- linux
- windows
- osx
language: python
python:
- 3.7
- 3.6
- 2.7
cache: pip
addons:
  apt:
    packages:
    - ffmpeg
    - sox
before_install: pip install cython # TODO This shouldn't be needed.
install: pip install .
before_script:
- pip install joblib==0.11  # TODO Remove this line when librosa 0.6.2 is released (see https://github.com/librosa/librosa/issues/732#issuecomment-400669539)
- pip install pytest-cov librosa
script:
- pytest --cov=pysndfx
deploy:
  provider: pypi
  user: carlthome
  skip_cleanup: true
  on:
    tags: true
    branch: master
  password:
    secure: EIVQp6DdA6CzKyIuFwzBekGmab/XUUs/9uFK6N1ejQA2219b3NNmogbkvFX1ZWE1sRmhA5PXV5vdToljAXfvL76AyVW01MNT5i6HLb1S4XzwuJYVdGBSFTQYcvgOLBz6yrkAwyuDZ6E9FLGQYEq51+SmD1yA531u8HA24l/RLozLY4cpnNIDoLsKtb9pj20LlwcprmTYFZBIL153z2oap975Vb09QV2qqJ0cL5irjGCUqI4spkzVY2QjA6TnfN0xwLw5XoESJoTY3R8L3cJ8B4JhvUwNsxNZxLY8ik22iRYQ+vUxGbpzYSDZ9WJsPzEqzRf6JHMnydF4qVH9kbXkBPNCUVh/AkBrXbE8YvbyO9P4mwoc55y7Ikpyk4Z5NuJQDVnGvcnySIvnhmNLQk6g1fpKZpydivWN+ZQEyVkCETApNOzMqzOqZaj+Z2my87Kn5rlwhELSNQGygudxtqaBh7EmDmUBYXBMaRIWsu6nquODlwLqImJkHaLH7rAmHQphIppO/QmCqVunFA+UPj+ZMUa7unqnTXuiMefCruTaVH0BAcrrNG8vx49O6rrhg3cW1dPkNb3oGOXuynwN+wXF2lBnfIqTube02hO5YcfyDQW7O9Hru/lBA1j2/n3PMn6TVoRTVqV/+SzU28XeoDOcbqhOMoeWFRrq90Fe9mLpP78=
