sudo: true
dist: xenial
language: sh
os:
- linux
- windows
- osx
before_install: |
  if [[ $TRAVIS_OS_NAME == 'windows' ]]
  then
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe
    Miniconda3-latest-Windows-x86_64.exe /S /D=%UserProfile%\Miniconda3    
    python -m ensurepip
    choco install ffmpeg sox.portable
  elif [[ $TRAVIS_OS_NAME == 'linux' ]]
  then
    sudo apt-get install -y ffmpeg sox
  elif [[ $TRAVIS_OS_NAME == 'osx' ]]
  then
    brew install ffmpeg sox
    export PATH=$PATH:/Users/travis/Library/Python/2.7/bin
  fi
install: pip install --user -e .
before_script: pip install --user pytest pytest-cov pytest-flake8 librosa
script: pytest --flake8 --cov=pysndfx tests/
deploy:
  provider: pypi
  user: carlthome
  skip_cleanup: true
  on:
    tags: true
    branch: master
  password:
    secure: EIVQp6DdA6CzKyIuFwzBekGmab/XUUs/9uFK6N1ejQA2219b3NNmogbkvFX1ZWE1sRmhA5PXV5vdToljAXfvL76AyVW01MNT5i6HLb1S4XzwuJYVdGBSFTQYcvgOLBz6yrkAwyuDZ6E9FLGQYEq51+SmD1yA531u8HA24l/RLozLY4cpnNIDoLsKtb9pj20LlwcprmTYFZBIL153z2oap975Vb09QV2qqJ0cL5irjGCUqI4spkzVY2QjA6TnfN0xwLw5XoESJoTY3R8L3cJ8B4JhvUwNsxNZxLY8ik22iRYQ+vUxGbpzYSDZ9WJsPzEqzRf6JHMnydF4qVH9kbXkBPNCUVh/AkBrXbE8YvbyO9P4mwoc55y7Ikpyk4Z5NuJQDVnGvcnySIvnhmNLQk6g1fpKZpydivWN+ZQEyVkCETApNOzMqzOqZaj+Z2my87Kn5rlwhELSNQGygudxtqaBh7EmDmUBYXBMaRIWsu6nquODlwLqImJkHaLH7rAmHQphIppO/QmCqVunFA+UPj+ZMUa7unqnTXuiMefCruTaVH0BAcrrNG8vx49O6rrhg3cW1dPkNb3oGOXuynwN+wXF2lBnfIqTube02hO5YcfyDQW7O9Hru/lBA1j2/n3PMn6TVoRTVqV/+SzU28XeoDOcbqhOMoeWFRrq90Fe9mLpP78=
